#!/bin/sh
#-----------------------------------------------------------------------------

echo 'Content-Type: text/html'
echo
echo '<html><body>'
echo '<h2>Simple Script</h2>'
echo '<p>[<a href="/">home</a>]</p>'
echo '<hr>'
echo '<p>Current date: <tt>'
date
echo '</tt></p>'
echo '<hr>'
echo '<p>Current process list:</p>'
echo '<pre>'
ps axf | sed -e 's/</\&lt;/g'
echo '</pre>'
echo '<hr>'
echo '</body></html>'

#-----------------------------------------------------------------------------
